import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./providerWrapper";
import { NextUIProvider } from "@nextui-org/react";
// import {NextUIProvider} from "@nextui-org/system";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderWrapper>
          <NextUIProvider>
          {children}
          </NextUIProvider>
        </ProviderWrapper>
        </body>
    </html>
  );
}
